local dir = os.getenv("HOME") .. "/.config/awesome/theme/icons"

return {
  --tags
  chrome = dir .. "/google-chrome.svg",
  code = dir .. "/code-braces.svg",
  social = dir .. "/forum.svg",
  folder = dir .. "/folder.svg",
  music = dir .. "/music.svg",
  game = dir .. "/google-controller.svg",
  lab = dir .. "/flask.svg",
  --others
  menu = dir .. "/menu.svg",
  close = dir .. "/close.svg",
  logout = dir .. "/logout.svg",
  sleep = dir .. "/power-sleep.svg",
  power = dir .. "/power.svg",
  lock = dir .. "/lock.svg",
  restart = dir .. "/restart.svg",
  search = dir .. "/magnify.svg",
  volume = dir .. "/volume-high.svg",
  brightness = dir .. "/brightness-7.svg",
  chart = dir .. "/chart-areaspline.svg",
  memory = dir .. "/memory.svg",
  harddisk = dir .. "/harddisk.svg",
  thermometer = dir .. "/thermometer.svg",
  plus = dir .. "/plus.svg",
  package = dir .. "/package.svg",
  packageUp = dir .. "/package-up.svg",
  volumeMuted = dir .. "/volume-muted.svg",
  volumeLow = dir .. "/volume-muted.svg",
  volumeMedium = dir .. "/volume-low.svg",
  volumeHigh = dir .. "/volume-medium.svg",
  volumeFull = dir .. "/volume-high.svg",
  battery0 = dir .. "battery/battery-0.svg",
  battery25 = dir .. "/battery/battery-25.svg",
  battery50 = dir .. "/battery/battery-50.svg",
  battery75 = dir .. "/battery/battery-75.svg",
  battery100 = dir .. "/battery/battery-100.svg",
  batteryCharging0 = dir .. "battery/battery-charging-0.svg",
  batteryCharging25 = dir .. "/battery/battery-charging-25.svg",
  batteryCharging50 = dir .. "/battery/battery-charging-50.svg",
  batteryCharging75 = dir .. "/battery/battery-charging-75.svg",
  batteryCharging100 = dir .. "/battery/battery-charging-100.svg",
  batteryAlert = dir .. "/battery/battery-alert.svg",
  networkOff = dir .. "/wifi-off.svg",
  networkAlert = dir .. "/wifi-alert.svg",
  networkConnected = dir .. "/wifi-connected.svg"
}
